-- Generated by backend/src/scripts/generate-plan-import-sql.ts
-- Source workbook: C:\Users\lcliu\Desktop\数据表.xlsx
-- Generated at: 2026-04-21T05:49:15.161Z

begin;

do $$
declare
  target_email text := '1328119115@qq.com';
  import_year int := 2026;
  target_profile_id uuid;
  current_week_id uuid;
  current_session_id uuid;
begin
  select id into target_profile_id
  from public.profiles
  where email = target_email;

  if target_profile_id is null then
    raise exception 'Target profile not found for email: %', target_email;
  end if;

  delete from public.training_weeks where user_id = target_profile_id;

  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 40)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '扣篮', 0, 0, '', 0),
    (current_session_id, '卧推', 5, 8, '65kg', 1),
    (current_session_id, '上斜卧推', 4, 10, '50kg', 2),
    (current_session_id, '俯卧撑', 4, 10, '10kg', 3),
    (current_session_id, '杠铃弯举', 6, 10, '30kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 5, 8, '90kg', 0),
    (current_session_id, '颈前预蹲', 4, 4, '100kg', 1),
    (current_session_id, '单脚硬拉', 4, 10, '10kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '对握引体', 3, 8, '15kg', 0),
    (current_session_id, '颈后引体', 2, 10, '', 1),
    (current_session_id, '潘德雷划船', 4, 10, '70kg', 2),
    (current_session_id, '借力推', 4, 4, '50kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 5, 8, '60kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1),
    (current_session_id, '俯卧撑', 4, 12, '10kg', 2),
    (current_session_id, '杠铃弯举', 4, 10, '30kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 5, 2, '90kg', 0),
    (current_session_id, '颈前预蹲', 4, 4, '110kg', 1),
    (current_session_id, '单脚硬拉', 4, 10, '20kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '颈后引体', 5, 10, '', 0),
    (current_session_id, '潘德雷划船', 4, 10, '70kg', 1),
    (current_session_id, '借力推', 4, 4, '50kg', 2),
    (current_session_id, '吕小军飞鸟', 6, 15, '5kg', 3);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 41)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '扣篮', 0, 0, '', 0),
    (current_session_id, '卧推', 5, 8, '70kg', 1),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 2),
    (current_session_id, '杠铃弯举', 6, 10, '30kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 5, 8, '95kg', 0),
    (current_session_id, '颈前预蹲', 1, 4, '120kg', 1),
    (current_session_id, '颈前预蹲', 3, 4, '130kg', 2),
    (current_session_id, '过头蹲', 3, 5, '40kg', 3),
    (current_session_id, '单脚硬拉', 4, 10, '20kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '对握引体', 3, 8, '20kg', 0),
    (current_session_id, '颈后引体', 2, 10, '', 1),
    (current_session_id, '潘德雷划船', 4, 10, '70kg', 2),
    (current_session_id, '借力推', 4, 4, '50kg', 3),
    (current_session_id, '吕小军飞鸟', 4, 10, '5kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 5, 8, '65kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1),
    (current_session_id, '俯卧撑', 2, 10, '20kg', 2),
    (current_session_id, '杠铃弯举', 6, 10, '25kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 1, 2, '95kg', 0),
    (current_session_id, '高翻', 4, 2, '90kg', 1),
    (current_session_id, '前蹲', 2, 6, '80kg', 2),
    (current_session_id, '深蹲', 2, 6, '80kg', 3),
    (current_session_id, '借力推', 4, 4, '50kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '颈后引体', 5, 12, '', 0),
    (current_session_id, '潘德雷划船', 4, 10, '70kg', 1),
    (current_session_id, '吕小军飞鸟', 3, 15, '5kg', 2),
    (current_session_id, '俯身飞鸟', 3, 15, '5kg', 3);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 42)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 5, 8, '75kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 5, 8, '100kg', 0),
    (current_session_id, '架上四分之一蹲', 4, 4, '170kg', 1),
    (current_session_id, '单脚硬拉', 4, 10, '30kg', 2),
    (current_session_id, '颈后爆发上推', 2, 4, '60kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 8, '15kg', 0),
    (current_session_id, '颈后引体', 2, 10, '', 1),
    (current_session_id, '潘德雷划船', 4, 10, '75kg', 2),
    (current_session_id, '吕小军飞鸟', 4, 15, '5kg', 3),
    (current_session_id, '俯身飞鸟', 4, 15, '5kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 5, 8, '70kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1),
    (current_session_id, '杠铃弯举', 6, 10, '25kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 2, 2, '95kg', 0),
    (current_session_id, '高翻', 3, 2, '90kg', 1),
    (current_session_id, '深蹲', 3, 6, '90kg', 2),
    (current_session_id, '颈后爆发上推', 3, 4, '60kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '颈后引体', 5, 12, '', 0),
    (current_session_id, '潘德雷划船', 4, 10, '75kg', 1),
    (current_session_id, '吕小军飞鸟', 6, 10, '5kg', 2),
    (current_session_id, '俯身飞鸟', 6, 10, '5kg', 3);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 43)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 5, 8, '75kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1),
    (current_session_id, '杠铃弯举', 5, 10, '25kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 5, 8, '105kg', 0),
    (current_session_id, '架上四分之一蹲', 4, 4, '180kg', 1),
    (current_session_id, '单脚硬拉', 4, 10, '30kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 8, '15kg', 0),
    (current_session_id, '颈后引体', 2, 8, '', 1),
    (current_session_id, '潘德雷划船', 4, 10, '75kg', 2),
    (current_session_id, '吕小军飞鸟', 3, 10, '5kg', 3),
    (current_session_id, '俯身飞鸟', 3, 10, '5kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 5, 8, '70kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1),
    (current_session_id, '杠铃弯举', 6, 10, '25kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 44)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 3, 8, '50kg', 0),
    (current_session_id, '上斜卧推', 2, 10, '40kg', 1),
    (current_session_id, '杠铃弯举', 3, 10, '20kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 3, 8, '80kg', 0),
    (current_session_id, '高翻', 3, 3, '60kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 8, '', 0),
    (current_session_id, '潘德雷划船', 2, 10, '40kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 3, 8, '50kg', 0),
    (current_session_id, '上斜卧推', 2, 10, '40kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '70kg', 0);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 8, '', 0),
    (current_session_id, '潘德雷划船', 2, 10, '40kg', 1);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 45)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 5, 8, '65kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '50kg', 1),
    (current_session_id, '双杠臂屈伸', 2, 10, '', 2),
    (current_session_id, '杠铃弯举', 6, 10, '25kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 5, 8, '90kg', 0),
    (current_session_id, '高翻', 3, 2, '70kg', 1),
    (current_session_id, '单脚硬拉', 4, 10, '30kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 5, 12, '', 0),
    (current_session_id, '水平划船', 4, 10, '11片', 1),
    (current_session_id, '吕小军飞鸟', 6, 15, '5kg', 2),
    (current_session_id, '俯身飞鸟', 6, 15, '5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 5, 8, '60kg', 0),
    (current_session_id, '上斜卧推', 4, 10, '55kg', 1),
    (current_session_id, '哑铃弯举', 4, 12, '10kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '90kg', 0),
    (current_session_id, '深蹲', 3, 4, '112.5kg', 1),
    (current_session_id, '跳神（快）', 4, 4, '', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '15kg', 0),
    (current_session_id, '水平划船', 2, 10, '12片', 1),
    (current_session_id, '哑铃推肩', 2, 10, '20kg', 2);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 46)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '80kg', 0),
    (current_session_id, '卧推', 3, 5, '75kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2),
    (current_session_id, '哑铃弯举', 4, 12, '10kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 3, 3, '120kg', 0),
    (current_session_id, '高翻', 3, 2, '80kg', 1),
    (current_session_id, '单脚臀桥', 2, 10, '25kg', 2),
    (current_session_id, '跳深（快）', 4, 4, '', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '20kg', 0),
    (current_session_id, '水平划船', 2, 10, '13片', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2),
    (current_session_id, '吕小军飞鸟', 3, 10, '5kg', 3),
    (current_session_id, '俯身飞鸟', 3, 10, '5kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '75kg', 0),
    (current_session_id, '窄推', 3, 5, '70kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2),
    (current_session_id, '哑铃弯举', 2, 10, '12.5kg', 3),
    (current_session_id, '哑铃弯举', 2, 10, '10kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '90kg', 0),
    (current_session_id, '深蹲', 3, 3, '115kg', 1),
    (current_session_id, '跳深（快）', 4, 4, '', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '25kg', 0),
    (current_session_id, '水平划船', 2, 10, '13片', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2),
    (current_session_id, '吕小军飞鸟', 2, 10, '5kg', 3),
    (current_session_id, '俯身飞鸟', 2, 10, '5kg', 4);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 47)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '82.5kg', 0),
    (current_session_id, '卧推', 3, 5, '77.5kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 3, 3, '120kg', 0),
    (current_session_id, '高翻', 3, 2, '80kg', 1),
    (current_session_id, '单脚硬拉', 2, 10, '30kg', 2),
    (current_session_id, '跳深（快）', 4, 4, '', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '25kg', 0),
    (current_session_id, '水平划船', 2, 10, '14片', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2),
    (current_session_id, '吕小军飞鸟', 3, 10, '5kg', 3),
    (current_session_id, '俯身飞鸟', 3, 10, '5kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '77.5kg', 0),
    (current_session_id, '窄推', 3, 5, '72.5kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 2, 2, '90kg', 0),
    (current_session_id, '高翻', 1, 2, '95kg', 1),
    (current_session_id, '深蹲', 3, 3, '115kg', 2),
    (current_session_id, '跳深', 4, 4, '', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 1, 5, '30kg', 0),
    (current_session_id, '引体', 3, 5, '27.5kg', 1),
    (current_session_id, '水平划船', 2, 10, '14片', 2),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 3),
    (current_session_id, '实力推', 2, 5, '40kg', 4);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 48)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '85kg', 0),
    (current_session_id, '卧推', 3, 5, '80kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2),
    (current_session_id, '哑铃弯举', 4, 12, '10kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '120kg', 0),
    (current_session_id, '深蹲', 3, 5, '115kg', 1),
    (current_session_id, '单脚硬拉', 2, 10, '30kg', 2),
    (current_session_id, '双倍跳箱', 4, 4, '', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '30kg', 0),
    (current_session_id, '水平划船', 2, 10, '14片', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '80kg', 0),
    (current_session_id, '窄推', 3, 5, '75kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '92.5kg', 0),
    (current_session_id, '深蹲', 3, 5, '110kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '30kg', 0),
    (current_session_id, '水平划船', 2, 10, '14片', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 49)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '87.5kg', 0),
    (current_session_id, '卧推', 2, 5, '82.5kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '125kg', 0),
    (current_session_id, '深蹲', 1, 3, '120kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 50)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 3, 5, '70kg', 0);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 2, 5, '100kg', 0);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 3, 5, '65kg', 0);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 2, 2, '80kg', 0),
    (current_session_id, '深蹲', 2, 5, '90kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 51)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '80kg', 0),
    (current_session_id, '卧推', 2, 5, '75kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '12.5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '110kg', 0),
    (current_session_id, '深蹲', 3, 5, '100kg', 1),
    (current_session_id, '高翻', 2, 2, '90kg', 2),
    (current_session_id, '髋外展', 2, 15, '', 3),
    (current_session_id, '髋内收', 2, 15, '', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '20kg', 0),
    (current_session_id, '水平划船', 2, 10, '', 1),
    (current_session_id, '高位下拉', 2, 10, '70kg', 2),
    (current_session_id, '哑铃推肩', 2, 10, '20kg', 3),
    (current_session_id, '面拉', 4, 12, '', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '75kg', 0),
    (current_session_id, '窄推', 3, 5, '70kg', 1),
    (current_session_id, '上斜卧推', 2, 10, '60kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '12.5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 2, 2, '90kg', 0),
    (current_session_id, '深蹲', 3, 5, '90kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '20kg', 0),
    (current_session_id, '反手高位下拉', 2, 8, '75kg', 1),
    (current_session_id, '坐姿划船', 2, 10, '65kg', 2),
    (current_session_id, '面拉', 4, 15, '', 3);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 52)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '80kg', 0),
    (current_session_id, '卧推', 3, 5, '75kg', 1),
    (current_session_id, '无腿卧推', 3, 8, '60kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '10kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '110kg', 0),
    (current_session_id, '深蹲', 3, 5, '100kg', 1),
    (current_session_id, '高翻', 2, 2, '80kg', 2),
    (current_session_id, '髋外展', 2, 15, '59kg', 3),
    (current_session_id, '髋内收', 2, 15, '30kg', 4),
    (current_session_id, '哥本哈根支撑', 2, 30, '', 5);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '20kg', 0),
    (current_session_id, '反手高位下拉', 2, 10, '68kg', 1),
    (current_session_id, '潘德雷划船', 2, 8, '60kg', 2),
    (current_session_id, '哑铃推肩', 2, 10, '20kg', 3),
    (current_session_id, '面拉', 4, 15, '18kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '75kg', 0),
    (current_session_id, '窄推', 3, 5, '70kg', 1),
    (current_session_id, '无腿窄推', 3, 8, '55kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '12.5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '90kg', 0),
    (current_session_id, '高翻', 2, 5, '60kg', 1),
    (current_session_id, '深蹲', 3, 5, '100kg', 2),
    (current_session_id, '髋外展', 2, 15, '64kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '20kg', 0),
    (current_session_id, '反手高位下拉', 2, 8, '68kg', 1),
    (current_session_id, '潘德雷划船', 2, 10, '60kg', 2),
    (current_session_id, '哑铃推肩', 2, 10, '20kg', 3),
    (current_session_id, '面拉', 4, 15, '18kg', 4);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 53)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '82.5kg', 0),
    (current_session_id, '卧推', 3, 5, '77.5kg', 1),
    (current_session_id, '无腿卧推', 2, 8, '60kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '115kg', 0),
    (current_session_id, '深蹲', 3, 5, '105kg', 1),
    (current_session_id, '高翻', 2, 3, '80kg', 2),
    (current_session_id, '哥本哈根支撑', 2, 30, '', 3),
    (current_session_id, '髋内收', 2, 15, '30kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '25kg', 0),
    (current_session_id, '反手高位下拉', 2, 10, '68kg', 1),
    (current_session_id, '潘德雷划船', 2, 10, '60kg', 2),
    (current_session_id, '哑铃推肩', 2, 12, '22.5kg', 3),
    (current_session_id, '面拉', 4, 15, '18kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '77.5kg', 0),
    (current_session_id, '窄推', 3, 5, '72.5kg', 1),
    (current_session_id, '无腿窄推', 2, 8, '60kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '12.5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '90kg', 0),
    (current_session_id, '深蹲', 3, 5, '100kg', 1),
    (current_session_id, '髋内收', 2, 15, '36kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '25kg', 0),
    (current_session_id, '反手高位下拉', 2, 8, '68kg', 1),
    (current_session_id, '潘德雷划船', 2, 10, '60kg', 2),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 3),
    (current_session_id, '面拉', 4, 15, '18kg', 4);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 54)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '85kg', 0),
    (current_session_id, '卧推', 3, 5, '80kg', 1),
    (current_session_id, '无腿卧推', 2, 8, '65kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '12.5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '120kg', 0),
    (current_session_id, '深蹲', 3, 5, '110kg', 1),
    (current_session_id, '高翻', 2, 2, '80kg', 2),
    (current_session_id, '哥本哈根支撑', 2, 30, '', 3),
    (current_session_id, '髋内收', 2, 15, '30kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '25kg', 0),
    (current_session_id, '反手高位下拉', 2, 8, '68kg', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2),
    (current_session_id, '面拉', 4, 15, '18kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '80kg', 0),
    (current_session_id, '窄推', 3, 5, '75kg', 1),
    (current_session_id, '无腿窄推', 2, 10, '65kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '12.5kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 1, 2, '95kg', 0),
    (current_session_id, '高翻', 2, 3, '90kg', 1),
    (current_session_id, '四分之一蹲', 3, 4, '160kg', 2),
    (current_session_id, '罗拉', 2, 6, '100kg', 3),
    (current_session_id, '髋内收', 2, 15, '36kg', 4),
    (current_session_id, '哥本哈根支撑', 2, 35, '', 5);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '30kg', 0),
    (current_session_id, '反手高位下拉', 2, 10, '68kg', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2),
    (current_session_id, '面拉', 2, 15, '18kg', 3);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 55)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 1, 3, '85kg', 0),
    (current_session_id, '卧推', 3, 5, '80kg', 1),
    (current_session_id, '无腿卧推', 2, 8, '70kg', 2),
    (current_session_id, '哑铃弯举', 2, 12, '15kg', 3);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 1, 3, '120kg', 0),
    (current_session_id, '深蹲', 3, 5, '', 1),
    (current_session_id, '高翻', 3, 2, '80kg', 2),
    (current_session_id, '哥本哈根支撑', 2, 35, '', 3),
    (current_session_id, '髋内收', 2, 15, '30kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高位下拉', 3, 5, '78kg', 0),
    (current_session_id, '反手高位下拉', 2, 10, '68kg', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 1, 3, '80kg', 0),
    (current_session_id, '窄推', 3, 5, '75kg', 1),
    (current_session_id, '无腿窄推', 2, 8, '60kg', 2),
    (current_session_id, '无腿窄推', 1, 11, '65kg', 3),
    (current_session_id, '哑铃弯举', 2, 12, '15kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 3, 2, '95kg', 0),
    (current_session_id, '高翻', 1, 5, '80kg', 1),
    (current_session_id, '深蹲', 1, 5, '100kg', 2),
    (current_session_id, '深蹲', 1, 12, '100kg', 3),
    (current_session_id, '髋内收', 2, 15, '30kg', 4);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '引体', 3, 5, '30kg', 0),
    (current_session_id, '引体', 1, 11, '10kg', 1),
    (current_session_id, '哑铃推肩', 2, 10, '22.5kg', 2);
  insert into public.training_weeks (user_id, training_year, week_number)
  values (target_profile_id, import_year, 56)
  returning id into current_week_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第一次训练', 0)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '卧推', 2, 5, '70kg', 0),
    (current_session_id, '无腿卧推', 1, 8, '60kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第二次训练', 1)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '深蹲', 2, 5, '100kg', 0),
    (current_session_id, '高翻', 2, 2, '80kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第三次训练', 2)
  returning id into current_session_id;

  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第四次训练', 3)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '窄推', 2, 5, '65kg', 0),
    (current_session_id, '无腿窄推', 2, 8, '60kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第五次训练', 4)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '高翻', 2, 2, '80kg', 0),
    (current_session_id, '深蹲', 1, 5, '90kg', 1);
  insert into public.training_sessions (week_id, title, order_index)
  values (current_week_id, '第六次训练', 5)
  returning id into current_session_id;

  insert into public.training_exercises (session_id, name, sets, reps, load, order_index)
  values
    (current_session_id, '反手引体', 2, 5, '', 0);
end $$;

commit;
